[tool.poetry]
name = "pypattern"
version = "0.1.0"
description = "Design Patterns"
authors = ["sacklippe"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
